package com.chunbo.codegenerator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-10T18:45:01.221+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://codegenerator.chunbo.com/", name = "SerialNumberGenerator")
@XmlSeeAlso({ObjectFactory.class})
public interface SerialNumberGenerator {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generateNumber", targetNamespace = "http://codegenerator.chunbo.com/", className = "com.chunbo.codegenerator.GenerateNumber")
    @WebMethod
    @ResponseWrapper(localName = "generateNumberResponse", targetNamespace = "http://codegenerator.chunbo.com/", className = "com.chunbo.codegenerator.GenerateNumberResponse")
    public long generateNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNextLongNumber", targetNamespace = "http://codegenerator.chunbo.com/", className = "com.chunbo.codegenerator.GetNextLongNumber")
    @WebMethod
    @ResponseWrapper(localName = "getNextLongNumberResponse", targetNamespace = "http://codegenerator.chunbo.com/", className = "com.chunbo.codegenerator.GetNextLongNumberResponse")
    public long getNextLongNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
